# Generated by Django 5.1.7 on 2025-03-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropFixedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, unique=True)),
                ('min_tds', models.FloatField()),
                ('max_tds', models.FloatField()),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('min_water_temp', models.FloatField()),
                ('max_water_temp', models.FloatField()),
                ('min_atmosphere_temp', models.FloatField()),
                ('max_atmosphere_temp', models.FloatField()),
                ('growth_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CultivatingCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_tds', models.FloatField()),
                ('current_ph', models.FloatField()),
                ('current_humidity', models.FloatField()),
                ('current_water_temp', models.FloatField()),
                ('current_atmosphere_temp', models.FloatField()),
                ('status', models.CharField(choices=[('Growing', 'Growing'), ('Harvested', 'Harvested')], default='Growing', max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.cropfixedvalues')),
            ],
        ),
    ]
